config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searchs#search"

  resources :books, only: %i[index show edit create destroy update] do
    resource :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create destroy]
  end

  resources :users, only: %i[index show edit update] do
    member { get :follows, :followers }
  end

  resources :relationships, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :ensure_correct_user, only: [:destroy]

  def create
    @book = Book.find(params[:book_id])
    @book_comment = @book.book_comments.new(book_comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.save
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_back fallback_location: books_path
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

  def ensure_correct_user
    book_comment = BookComment.find(params[:id])
    unless book_comment.user == current_user
      redirect_to book_path(book_comment.book)
    end
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
<div class="clearfix">
  <div class="float-left mr-1">
    <%= link_to(book_comment.user) do %>
      <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
      <%= book_comment.user.name %>
    <% end %>
  </div>
  <div>
    <%= book_comment.comment %>
    <% if book_comment.user == current_user %>
      <%= link_to "Destroy", book_book_comment_path(@book, book_comment), method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/book_comments/_form.html.erb
<%= form_with model: [@book, @book_comment], local: false do |f| %>
  <div class="form-group">
    <%= f.text_area :comment, class: 'form-control', id: 'comment-input' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/book_comments/create.js.erb
$('.comments').append("<%= j(render 'book_comments/comment', book: @book, book_comment: @book_comment) %>");
$('#comment-input').val('');

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>