config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searchs#search"

  resources :books, only: %i[index show edit create destroy update] do
    resource :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create destroy]
  end

  resources :users, only: %i[index show edit update] do
    member { get :follows, :followers }
  end

  resources :relationships, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :rate, presence: true, numericality: { in: 1..5 }, on: :create
  validates :tag, presence: true
  validate :rate_not_changed, on: :update

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  private

  def rate_not_changed
    errors.add(:rate, "は変更できません。") if rate_changed?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: %i[edit update destroy]

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def index
    sort = params.fetch(:sort, "new")
    case sort
    when "new"
      order = { id: "DESC" }
    when "rate"
      order = { rate: "DESC" }
    else
    end

    @books = Book.all.order(order)
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book),
                  notice: "You have created book successfully."
    else
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book),
                  notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :tag)
  end

  def ensure_correct_user
    book = Book.find(params[:id])
    redirect_to books_path unless book.user == current_user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment_count.html.erb
コメント数：<%= book.book_comments.count %>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    <span class="text-danger">♥<%= book.favorites.count %></span>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: book, local:true do |f| %>
  <%= render 'layouts/errors', obj: book %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :tag %>
    <%= f.text_field :tag, class: 'form-control book_tag' %>
  </div>
  <% if book.new_record? %>
    <div class="form-group">
      <%= f.label :rate %>
      <%= f.select :rate, (1..5).to_a %>
    </div>
  <% else %>
    <div class="form-group">
      <%= render "books/rate_star", book: book %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= link_to book.tag, search_path(tag: book.tag) %></td>
        <td><%= render "favorites/favorite-btn", book: book %></td>
        <td><%= render "books/comment_count", book: book %></td>
        <td><%= render "books/rate_star", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_rate_star.html.erb
<div style="color: orange;">
  <% if book.rate.present? %>
    <%== '<i class="fas fa-star"></i>' * book.rate %><%== '<i class="far fa-star"></i>' * (5 - book.rate) %>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <div>
        <%= link_to '新しい順', books_path(sort: 'new') %> | <%= link_to '評価の高い順', books_path(sort: 'rate') %>
      </div>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= link_to @book.tag, search_path(tag: @book.tag) %></td>
          <td><%= render "favorites/favorite-btn", book: @book %></td>
          <td><%= render "comment_count", book: @book %></td>
          <td><%= render "books/rate_star", book: @book %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>

      <div class="comments">
        <% @book.book_comments.each do |book_comment| %>
          <%= render "book_comments/comment", book_comment: book_comment %>
        <% end %>
      </div>

      <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>