config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searchs#search"

  resources :books, only: %i[index show edit create destroy update] do
    resource :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create destroy]
  end

  resources :users, only: %i[index show edit update] do
    member { get :follows, :followers }
  end

  resources :relationships, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :rate, presence: true, numericality: { in: 1..5 }, on: :create
  validates :tag, presence: true
  validate :rate_not_changed, on: :update

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  private

  def rate_not_changed
    errors.add(:rate, "は変更できません。") if rate_changed?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
  belongs_to :follow, class_name: "User", foreign_key: "followed_id"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :books
  has_many :favorites
  has_many :relationships_for_followed,
           class_name: "Relationship",
           foreign_key: "follower_id",
           dependent: :destroy
  has_many :relationships_for_follower,
           class_name: "Relationship",
           foreign_key: "followed_id",
           dependent: :destroy
  has_many :follows, through: :relationships_for_followed, source: :follow
  has_many :followers, through: :relationships_for_follower, source: :follower
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : "no_image.jpg"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: %i[top about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def not_found
    raise ActionController::RoutingError.new("Not Found")
  end

  private

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: %i[edit update destroy]

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def index
    sort = params.fetch(:sort, "new")
    case sort
    when "new"
      order = { id: "DESC" }
    when "rate"
      order = { rate: "DESC" }
    else
    end

    @books = Book.all.order(order)
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book),
                  notice: "You have created book successfully."
    else
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book),
                  notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :tag)
  end

  def ensure_correct_user
    book = Book.find(params[:id])
    redirect_to books_path unless book.user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save()
    render "favorite-btn"
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    render "favorite-btn"
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    return book_tag_search(params[:tag]) if params.has_key?(:tag)

    @target = params[:target]

    case @target
    when "user"
      @items = User.where("name LIKE ?", like(params[:word], params[:type]))
    when "book"
      @items = Book.where("title LIKE ?", like(params[:word], params[:type]))
    else
      not_found
    end
  end

  private

  def book_tag_search(tag)
    @target = "book"
    @items = Book.where(tag: params[:tag])
  end

  def like(word, type)
    case type
    when "perfect"
      return word
    when "forward"
      return "#{word}%"
    when "backward"
      return "%#{word}"
    when "partial"
      return "%#{word}%"
    else
      not_found
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: %i[edit update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user),
                  notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follows
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> logout
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> about
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> login
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <% if user_signed_in? %>
    <div class="container px-5 px-sm-0">
      <div class="my-1">
        <form action="<%= search_path %>" class="form-inline float-left mr-3">
            <input type="text" name="word" class="form-control mr-1">
            <select name="target" class="form-control mr-1">
              <option value="user">User</option>
              <option value="book">Book</option>
            </select>
            <select name="type" class="form-control mr-1">
              <option value="perfect">完全一致</option>
              <option value="forward">前方一致</option>
              <option value="backward">後方一致</option>
              <option value="partial">部分一致</option>
            </select>
            <button class="btn btn-secondary" type="submit">検索</button>
        </form>
        <form action="<%= search_path %>" class="form-inline">
          <input type="text" name="tag" class="form-control mr-1">
          <button class="btn btn-secondary" type="submit">タグ検索</button>
        </form>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>